name: Fetch HTML with Requests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fetch-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the script
      run: python fetch_html.py

    - name: Upload output file
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: seats-html
        path: seats.html
